services:
  # Redpanda Broker: The core event streaming engine
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v23.2.1
    command:
      - redpanda start
      - --smp 1
      - --memory 512M
      - --overprovisioned
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda:9092,external://localhost:19092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:8080
      - --advertise-pandaproxy-addr internal://redpanda:8082,external://localhost:8080
    ports:
      - "8080:8080" # Redpanda HTTP Proxy
      - "19092:19092" # Kafka API (Use this port in your Go/Java code)
  redpanda-setup:
    image: docker.redpanda.com/redpandadata/redpanda:v23.2.1
    container_name: redpanda-setup
    depends_on:
      - redpanda
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        # Wait for Redpanda to be ready
        echo "Waiting for Redpanda..."
        until rpk cluster info --brokers redpanda:9092; do
          sleep 2
        done
        # Create the topic
        rpk topic create raw-tickers --brokers redpanda:9092
        echo "Topic 'raw-tickers' created successfully!"
  # Redpanda Console: The Web UI to see your data
  console:
    image: docker.redpanda.com/redpandadata/console:latest
    entrypoint: /bin/sh
    command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda:9092"]
    ports:
      - "8888:8080" # Access the UI at http://localhost:8888
    depends_on:
      - redpanda

  # TimescaleDB: Postgres optimized for time-series data
  edgewatch-db:
    image: timescale/timescaledb:latest-pg15
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  # Grafana: For the dashboard visualization
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - edgewatch-db
