apiVersion: 1
datasources:
  - name: PostgreSQL
    uid: edgewatch-db-983
    type: postgres
    url: edgewatch-db:5432
    database: postgres
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      sslmode: "disable"
      postgresVersion: 15
      timescaledb: true
